### ISSUE TITLE
questions about mobile / offline

### ISSUE THREAD

**Issue by joeblew99** [getsentry/raven-go#107]
I am looking something to catch all errors that occur on my golang clients.
I use web, desktop and mobile and code then all with golang.

I have a few questions, as i could not see the answers to these:

Do you have a gomobile version for android / ios ?

Do you have an offline version, so that errors are stored and then forwarded ?

**Comment by mattrobenolt** [comment]
We definitely don't have explicit support for using Go on Android or iOS and not entirely sure what, if anything, would need to be done.

And no, there's not support for offline processing directly in here, but wouldn't be terrible to bolt on as a Transport interface since that seems like a niche case and unlikely we'll support it natively anytime soon.

**Comment by joeblew99** [comment]
ok. 
thanks for clear answers.

gomobile is pretty easy.  Initially its weird, but damn its powerful when you hit the sweet spot.
this is a similar company to Sentry that has done it:
https://logpacker.com/blog/gomobile-library-development-for-ios-and-android
https://github.com/logpacker/mobile-sdk
