### ISSUE TITLE
Add public DNS support

### ISSUE THREAD

**Issue by snorberhuis** [getsentry/raven-go#127]
Currently I am using sentry to capture errors from a client application. I am unsure what sensitive information resides in the DNS, but for javascript a public DNS is available.

I want to use this public DNS in my go client. If there are problems with using the normal DNS>

**Comment by mattrobenolt** [comment]
First, it's DSN, not DNS. Very big difference. :)

Second, there's no point in Go using only the public DSN. The only difference is authentication with CORS which is very explicitly a browser thing. 

And to be explicit, the private DSN doesn't have read access or anything like that. All DSNs only allow write access for ingestion of events. There's no access to the rest of our API.

I'm going to add this to our FAQ since it comes up often enough.

**Comment by snorberhuis** [comment]
Thanks for the explanation. I did not see a FAQ or I would make a PR.
