### ISSUE TITLE
Is Master Stable for Production?

### ISSUE THREAD

**Issue by pacarvalho** [getsentry/raven-go#177]
Is the current master branch or any of other branches stable enough for use in a production environment? Are there plans for releasing a production version soon?

**Comment by mbyio** [comment]
I'm also wondering this. It actually seems pretty unstable. Eg. in https://github.com/getsentry/raven-go/pull/185 they merged a PR without actually knowing what it does. And in may PRs or issues, nobody from Sentry has even bothered to respond.

**Comment by mattrobenolt** [comment]
It's stable and people use it. In #185, there was some background that wasn't discussed on GitHub. Yes, I don't truly know what's going on, but it's not particularly important. I trust the person with the patch. They are using some tooling that I don't have personal experience with, so I don't have any strong opinions.

As for unaddressed PRs and issues, this is really hard for us right now. At the moment, we don't have a dedicated person on our team for raven-go. Go isn't used very heavily on our platform at the moment. I am the only one who even pokes at issues, while I don't write Go for my job anymore. I use it for side projects, but it's not a big part of my day to day anymore.

With that said, there's a reason why PRs sit open and issues unaddressed, because I'm not as comfortable merging them since I don't have the ability to commit the time needed to make sure they're correct and stable because I want to assure what exists does continue to work well.

**Comment by mbyio** [comment]
@mattrobenolt thanks for taking the time to respond and for clarifying. I'm sure it's super hard to maintain clients for so many languages/platforms.

**Comment by kamilogorek** [comment]
> As for unaddressed PRs and issues, this is really hard for us right now. At the moment, we don't have a dedicated person on our team for raven-go.

I'll try my best to change this though :)
And as the first step (well, second after applying all code tooling suggestions) I'm triaging all the issue and cleaning up our GH issues/PRs. Thus let me close this one and feel free to open new one if there are some specific questions. Cheers!
