### ISSUE TITLE
Log warning if SENTRY_DSN is not set

### ISSUE THREAD

**Issue by linusthe3rd** [getsentry/raven-go#85]
If the DSN is not configured for the client, no warning or message gets logged indicating that there is a problem. Compared to the python version of the raven library, a message DOES get logged indicating that the SENTRY_DSN has not been set in the codebase or environment variable.

To help users debug configuration issues, a message should be logged when raven-go does not get configured with a DSN.

**Comment by mattrobenolt** [comment]
This is fair. I can add this in.

**Comment by mattrobenolt** [comment]
So looking at what we do in python, we log when things _are_ configured.

And I'm hesitant to add logging into raven-go, strictly because there's no concept of log levels or filtering logs in your application. Whereas in python, there's a lot of control around logging and how things can be silenced if you don't want them ending up in stderr/stdout.

What if I added a `IsConfigured() bool` method to the `Client`? That seems like something that'd make a bit more sense imo.

**Comment by valentin-krasontovitsch** [comment]
The client's SetDSN method returns an error - if the passed dsn is empty, it returns nil.

I'm having a very hard time to see that this could be desired behaviour - effectively, the client fails setting up, yet a nil instead of an actual error is returned.

I'm not even talking about not logging this - I think it should fail (i.e. return an error) right then and there.

**Comment by valentin-krasontovitsch** [comment]
Hmm - is it because of how a client can be set up both [by supplying a dsn and by automatically reading an environment variable](https://github.com/getsentry/raven-go/blame/master/client.go#L343)?

**Comment by mattrobenolt** [comment]
It’s because an empty DSN is a valid value. An empty DSN means to have a working Client, but it doesn’t send anything. It’s just a way to noop. It’s also possible to setup as noop, then later call client.SetDSN to enable it, etc.

**Comment by valentin-krasontovitsch** [comment]
Ah, I see - cool, thanks for the info!

**Comment by kamilogorek** [comment]
Implemented. `raven.setDebug(true)` will turn on debug mode which will log that information now – https://github.com/getsentry/raven-go/blob/238ebd86338d2e91cb5c84663d695877dd5d0ff4/client.go#L382-L384
